### ISSUE TITLE
Cannot find event id 3 under /equipment

### ISSUE THREAD

**Issue by nichubbard** [padsley/k600analyser#144]
while sorting PR264 runs you get spammed with the following "error"
[Analyzer,ERROR] [mana.cxx:497:db_get_event_definition,ERROR] Cannot find event id 3 under /equipment

My understanding is this isn't really a problematic error, but as I find it a minor nuisance I was wondering if there was a quick change to the ODB/code that could be made to silence it? If not I will just put up with it.

**Comment by padsley** [comment]
Uh. Probably?

IIRC, it's the slow control data class. Things like beamline behaviours, magnetic fields etc.

Retief is the person for that.

**Comment by neveling** [comment]
Yes, it represents the epics beamline related info. It is defined as event ID 3 in analyzer.c
The problem should be fixed by adding an event 3 in the ODB.  I attach an example ODB file.
Had to change it to .txt to get GITHUB to accept it
[basic.odb.txt](https://github.com/padsley/k600analyser/files/522127/basic.odb.txt)

**Comment by nichubbard** [comment]
Thanks, that solved it. I'll push a commit to PR264 with this change included in a bit.
