### ISSUE TITLE
Github and Microsoft

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#163]
Hi everyone,

Github is being acquired with Microsoft. While I don't believe that this will lead to any problems in the short-to-medium term, my generalised hatred for That Company From Redmond means that I'm nervous about leaving the only version of the K600analyser on GitHub.

For this reason, I plan to (at some point) to mirror all of my repos onto GitLab (which has had its own problems but meh) just in case Microsoft decide to do what they did with Skype and make it functionally impossible to use.

At this point, no action is required. The GitHub repos will persist in being the "true" versions of the analyser. However, if you have your own version of the analyser living on GitHub somewhere, I suggest that you also take steps to back it up somewhere else.

Send me an e-mail if you're not sure what the hell I'm talking about and I'll try to explain better.

Noot noot.

**Comment by gauss345** [comment]
Yip... I knew about for awhile, but it seems to be confirmed only this week. I also doubt major changes to happen soon, since they'd lose user base almost immediately.

bitbucket is another option. Gitlab has its uses, but the idea behind git is distributive repo, so a remote isn't actually a big issue, as you can merge whenever ... :) 

I've also recently moved all my source to bitbucket, besides running my own repos at home/work.
midas also on bitbucket etc.
