### ISSUE TITLE
multiTDC

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#2]
Currently only accept events which are single hits in the TDC channels.

Need to deal with multiple hits per channel: accepting these events and choosing the TDC hit which is good.

**Comment by padsley** [comment]
From what RN has shown me earlier today, I think that this problem is fairly minor and so I'm not going to make fixing multiTDC hits a priority.

Note, however, that the Coulomb scattering cross section at backward angles increases strongly with Z (and to some extent with A) and thus this problem will likely be more pronounced at higher masses. Just sayin.

**Comment by padsley** [comment]
Post PR228B where the thresholds are lower and thus the number of multiple hit TDC events is higher, this stuff has now become an important issue.

Nic is looking at it (as he needs to) for the PR228B data. I hope that the developments that he makes to deal with the multihit part of the code should filter back into the repo. As such, I have assigned this job to him, at least for the moment.

**Comment by nichubbard** [comment]
I have made some adjustments to multi TDC code, which at least bring it back to a working state. Currently it only handles 1 "good" TDC hit per pulse, which seems to be fine for my situations. 
Is there a suggested branch to merge this code into? Master or a new branch or?

**Comment by nichubbard** [comment]
So I have pushed changes to multiTDC which just bring it back to a working state, and let the pulse window be configured in the config file.
At the moment multiple hits not in the 'good' window result in the first hit being selected (whatever that may be), and if there are multiple hits in the good window, the code will scream at you and not work.

Neither of these situations seem to matter much to me currently, but I guess they could be changed. The former could maybe prefer a hit closest to the good window, instead of random. As for the latter I am not sure what is best to do.

**Comment by padsley** [comment]
That is fine, at least for now.

I prefer a situation in which the code objects loudly to something funny
happening with multi-hit TDCs rather than something where it just quietly
goes awry without that being obvious.



Dr Philip Adsley MA MSci (Cantab)
Postdoctoral Research Fellow, University of Stellenbosch/iThemba LABS

**Comment by padsley** [comment]
I say (for now) that we close this issue and deal with the problem of multihit TDCs when it crops up.
